# Generated by Django 3.2.5 on 2021-07-10 03:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_in_idr', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('zoneid', models.IntegerField()),
                ('status', models.CharField(choices=[('BELUM DIBAYAR', 'BELUM DIBAYAR'), ('SUDAH DIBAYAR', 'SUDAH DIBAYAR'), ('DIPROSES', 'DIPROSES'), ('DITERIMA', 'DITERIMA'), ('DIKEMBALIKAN', 'DIKEMBALIKAN'), ('KADALUARSA', 'KADALUARSA')], default='BELUM DIBAYAR', max_length=20)),
                ('item', models.CharField(max_length=100)),
                ('pay_with', models.CharField(max_length=20)),
                ('nowa', models.CharField(max_length=20)),
                ('time_order', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code_name', models.CharField(max_length=20, unique=True)),
                ('image_url', models.URLField()),
            ],
        ),
    ]
