# Generated by Django 3.2.5 on 2021-07-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.payment'),
        ),
    ]
